# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /GMAT-R2015a

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /GMAT-R2015a

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /GMAT-R2015a/CMakeFiles /GMAT-R2015a/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /GMAT-R2015a/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GmatBase

# Build rule for target.
GmatBase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GmatBase
.PHONY : GmatBase

# fast build rule for target.
GmatBase/fast:
	$(MAKE) -f src/base/CMakeFiles/GmatBase.dir/build.make src/base/CMakeFiles/GmatBase.dir/build
.PHONY : GmatBase/fast

#=============================================================================
# Target rules for targets named GmatConsole

# Build rule for target.
GmatConsole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GmatConsole
.PHONY : GmatConsole

# fast build rule for target.
GmatConsole/fast:
	$(MAKE) -f src/console/CMakeFiles/GmatConsole.dir/build.make src/console/CMakeFiles/GmatConsole.dir/build
.PHONY : GmatConsole/fast

#=============================================================================
# Target rules for targets named GmatGUI

# Build rule for target.
GmatGUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GmatGUI
.PHONY : GmatGUI

# fast build rule for target.
GmatGUI/fast:
	$(MAKE) -f src/gui/CMakeFiles/GmatGUI.dir/build.make src/gui/CMakeFiles/GmatGUI.dir/build
.PHONY : GmatGUI/fast

#=============================================================================
# Target rules for targets named CInterface

# Build rule for target.
CInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CInterface
.PHONY : CInterface

# fast build rule for target.
CInterface/fast:
	$(MAKE) -f plugins/CInterfacePlugin/src/CMakeFiles/CInterface.dir/build.make plugins/CInterfacePlugin/src/CMakeFiles/CInterface.dir/build
.PHONY : CInterface/fast

#=============================================================================
# Target rules for targets named DataInterface

# Build rule for target.
DataInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DataInterface
.PHONY : DataInterface

# fast build rule for target.
DataInterface/fast:
	$(MAKE) -f plugins/DataInterfacePlugin/src/base/CMakeFiles/DataInterface.dir/build.make plugins/DataInterfacePlugin/src/base/CMakeFiles/DataInterface.dir/build
.PHONY : DataInterface/fast

#=============================================================================
# Target rules for targets named EphemPropagator

# Build rule for target.
EphemPropagator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EphemPropagator
.PHONY : EphemPropagator

# fast build rule for target.
EphemPropagator/fast:
	$(MAKE) -f plugins/EphemPropagatorPlugin/src/base/CMakeFiles/EphemPropagator.dir/build.make plugins/EphemPropagatorPlugin/src/base/CMakeFiles/EphemPropagator.dir/build
.PHONY : EphemPropagator/fast

#=============================================================================
# Target rules for targets named GmatEstimation

# Build rule for target.
GmatEstimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GmatEstimation
.PHONY : GmatEstimation

# fast build rule for target.
GmatEstimation/fast:
	$(MAKE) -f plugins/EstimationPlugin/src/base/CMakeFiles/GmatEstimation.dir/build.make plugins/EstimationPlugin/src/base/CMakeFiles/GmatEstimation.dir/build
.PHONY : GmatEstimation/fast

#=============================================================================
# Target rules for targets named EventLocator

# Build rule for target.
EventLocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EventLocator
.PHONY : EventLocator

# fast build rule for target.
EventLocator/fast:
	$(MAKE) -f plugins/EventLocatorPlugin/src/base/CMakeFiles/EventLocator.dir/build.make plugins/EventLocatorPlugin/src/base/CMakeFiles/EventLocator.dir/build
.PHONY : EventLocator/fast

#=============================================================================
# Target rules for targets named ExtraPropagators

# Build rule for target.
ExtraPropagators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExtraPropagators
.PHONY : ExtraPropagators

# fast build rule for target.
ExtraPropagators/fast:
	$(MAKE) -f plugins/ExtraPropagatorsPlugin/src/base/CMakeFiles/ExtraPropagators.dir/build.make plugins/ExtraPropagatorsPlugin/src/base/CMakeFiles/ExtraPropagators.dir/build
.PHONY : ExtraPropagators/fast

#=============================================================================
# Target rules for targets named Formation

# Build rule for target.
Formation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Formation
.PHONY : Formation

# fast build rule for target.
Formation/fast:
	$(MAKE) -f plugins/FormationPlugin/src/base/CMakeFiles/Formation.dir/build.make plugins/FormationPlugin/src/base/CMakeFiles/Formation.dir/build
.PHONY : Formation/fast

#=============================================================================
# Target rules for targets named GeometricMeasurements

# Build rule for target.
GeometricMeasurements: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GeometricMeasurements
.PHONY : GeometricMeasurements

# fast build rule for target.
GeometricMeasurements/fast:
	$(MAKE) -f plugins/GeometricMeasurementPlugin/src/base/CMakeFiles/GeometricMeasurements.dir/build.make plugins/GeometricMeasurementPlugin/src/base/CMakeFiles/GeometricMeasurements.dir/build
.PHONY : GeometricMeasurements/fast

#=============================================================================
# Target rules for targets named GmatFunction

# Build rule for target.
GmatFunction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GmatFunction
.PHONY : GmatFunction

# fast build rule for target.
GmatFunction/fast:
	$(MAKE) -f plugins/GmatFunctionPlugin/src/base/CMakeFiles/GmatFunction.dir/build.make plugins/GmatFunctionPlugin/src/base/CMakeFiles/GmatFunction.dir/build
.PHONY : GmatFunction/fast

#=============================================================================
# Target rules for targets named NewParameters

# Build rule for target.
NewParameters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NewParameters
.PHONY : NewParameters

# fast build rule for target.
NewParameters/fast:
	$(MAKE) -f plugins/NewParameterPlugin/src/base/CMakeFiles/NewParameters.dir/build.make plugins/NewParameterPlugin/src/base/CMakeFiles/NewParameters.dir/build
.PHONY : NewParameters/fast

#=============================================================================
# Target rules for targets named PolyhedronGravity

# Build rule for target.
PolyhedronGravity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PolyhedronGravity
.PHONY : PolyhedronGravity

# fast build rule for target.
PolyhedronGravity/fast:
	$(MAKE) -f plugins/PolyhedronGravityPlugin/src/base/CMakeFiles/PolyhedronGravity.dir/build.make plugins/PolyhedronGravityPlugin/src/base/CMakeFiles/PolyhedronGravity.dir/build
.PHONY : PolyhedronGravity/fast

#=============================================================================
# Target rules for targets named ProductionPropagators

# Build rule for target.
ProductionPropagators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProductionPropagators
.PHONY : ProductionPropagators

# fast build rule for target.
ProductionPropagators/fast:
	$(MAKE) -f plugins/ProductionPropagatorPlugin/src/base/CMakeFiles/ProductionPropagators.dir/build.make plugins/ProductionPropagatorPlugin/src/base/CMakeFiles/ProductionPropagators.dir/build
.PHONY : ProductionPropagators/fast

#=============================================================================
# Target rules for targets named PythonInterface

# Build rule for target.
PythonInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PythonInterface
.PHONY : PythonInterface

# fast build rule for target.
PythonInterface/fast:
	$(MAKE) -f plugins/PythonInterfacePlugin/src/base/CMakeFiles/PythonInterface.dir/build.make plugins/PythonInterfacePlugin/src/base/CMakeFiles/PythonInterface.dir/build
.PHONY : PythonInterface/fast

#=============================================================================
# Target rules for targets named SaveCommand

# Build rule for target.
SaveCommand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SaveCommand
.PHONY : SaveCommand

# fast build rule for target.
SaveCommand/fast:
	$(MAKE) -f plugins/SaveCommandPlugin/src/base/CMakeFiles/SaveCommand.dir/build.make plugins/SaveCommandPlugin/src/base/CMakeFiles/SaveCommand.dir/build
.PHONY : SaveCommand/fast

#=============================================================================
# Target rules for targets named Station

# Build rule for target.
Station: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Station
.PHONY : Station

# fast build rule for target.
Station/fast:
	$(MAKE) -f plugins/StationPlugin/src/base/CMakeFiles/Station.dir/build.make plugins/StationPlugin/src/base/CMakeFiles/Station.dir/build
.PHONY : Station/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GmatBase"
	@echo "... GmatConsole"
	@echo "... GmatGUI"
	@echo "... CInterface"
	@echo "... DataInterface"
	@echo "... EphemPropagator"
	@echo "... GmatEstimation"
	@echo "... EventLocator"
	@echo "... ExtraPropagators"
	@echo "... Formation"
	@echo "... GeometricMeasurements"
	@echo "... GmatFunction"
	@echo "... NewParameters"
	@echo "... PolyhedronGravity"
	@echo "... ProductionPropagators"
	@echo "... PythonInterface"
	@echo "... SaveCommand"
	@echo "... Station"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

